### ISSUE TITLE
Alternative for GMC

### ISSUE THREAD

**Issue by ViceTOP** [malonnnn/ServerConfig#1224]
Instead of using GMC for the Omnipotent heroes, such as Dr Manhattan, Christianic God (Depending on your point of view). Should get /i

What does /i do?

It spawns for the player an item by saying the id.

No worries about command blocks, they cant use them without op.

And why /i instead of gmc? Because tho they are omnipotent, they are not immortal. /gmc gives you "immortality".

**Comment by malonnnn** [comment]
this is reasonable and i approve. you may start replacing /gmc with /give (or /i) immediately.  

There will be the condition that we may roll back to GMC because /give is very powerful, even more powerful than GMC because you can spawn even more things. If this gets out of hand, we may have to roll back to GMC.
